spring.application.name=auditorfalhas

spring.datasource.url=jdbc:h2:mem:auditor_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

spring.jpa.hibernate.ddl-auto=update

spring.cloud.aws.region.static=sa-east-1
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}

spring.cloud.aws.sqs.enabled=true
spring.jpa.show-sql=true
aws.sqs.dlq-name=T02N_PAULA_KRUPINSKI_DLQ.fifo

